model:
  name: patchcore
  backbone: resnet18
  pre_trained: true
  layers:
    - layer2
    - layer3
  num_neighbors: 9

dataset:
  name: folder
  image:
    root: data/tilda
    train: train/good
    test: test
  image_size: 224

datamodule:
  num_workers: 0

trainer:
  accelerator: cpu
  devices: 1
  max_epochs: 1

logging:
  log_graph: false
